name: Build feature/develop branch

on:
  #Execute on push and manually.
  #push:
    #Only build automatically if pushed to the specified branches.
    #branches: 
    #- '**'
    #- develop
    #- main
  workflow_dispatch:

#Global environment variables.
env:
  VERSION_FILE: package.json

jobs:
  build-feature-branch:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure artifact repository credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    #Only needed to log in to private ECR repositories.
    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v2

    - name: Login to the artifact repository
      run: |
        aws ecr-public get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.ECR_REPOSITORY_URL }}

    - name: Validate version number
      run: |
        echo "Version file: ${VERSION_FILE}"

        #Read the version file.
        VERSION_NUMBER=$(jq -r '.version' ${VERSION_FILE} | tr -d '\n')

        #If node is installed in the runtime environment.
        #VERSION_NUMBER=$(node -p "require('./package.json').version") 
        
        #Append the version number variable to the array of runtime variables.
        echo "VERSION_NUMBER=VERSION_NUMBER" >> $GITHUB_ENV
        echo "Version number: ${VERSION_NUMBER}"
        
        #Allowed patterns.
        PATTERN="/([0-9]+\.[0-9]+\.[0]){1,1}/"

        if [[ ! ${VERSION_NUMBER} =~ $PATTERN ]]; then
          echo "❌ Version number ${VERSION_NUMBER} is inconsistent with the format. Exiting!"
          echo "Allowed formats: x.x.0"
          exit 1
        else
          echo "Version number ${VERSION_NUMBER} is consistent with the format"
        fi
      
    - name: Prepare image tag
      id: meta
      run: | 
        #Append the time stamp variable to the array of runtime variables.
        BUILD_TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP" >> $GITHUB_ENV
        echo "Build timestamp: ${BUILD_TIMESTAMP}"

        #Append the image digest.
        #SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)

        #Append the final tag to the array of runtime variables.
        IMAGE_TAG=${VERSION_NUMBER}-SNAPSHOT-${BUILD_TIMESTAMP}
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "Image tag: ${IMAGE_TAG}"

    - name: Build image
      run: |
        echo "Image name: ${{ vars.ECR_REPOSITORY_URL }}/${{ vars.ECR_REPOSITORY_GROUP }}/${{ vars.ECR_REPOSITORY_NAME }}:${IMAGE_TAG}"
        docker build -t ${{ vars.ECR_REPOSITORY_URL }}/${{ vars.ECR_REPOSITORY_GROUP }}/${{ vars.ECR_REPOSITORY_NAME }}:${IMAGE_TAG} .

    - name: Push image to artifact repository
      run: |
        docker push ${{ vars.ECR_REPOSITORY_URL }}/${{ vars.ECR_REPOSITORY_GROUP }}/${{ vars.ECR_REPOSITORY_NAME }}:${IMAGE_TAG}


  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Deploy on EC2 via SSH
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.EC2_HOST }}
  #         username: ${{ secrets.EC2_USERNAME }}
  #         key: ${{ secrets.EC2_KEY }}
  #         protocol: tcp
  #         port: 22
  #         script: |
  #           echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
  #           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/private:gh-action-app
  #           docker stop node-app || true
  #           docker rm node-app || true
  #           docker run -d --name node-app -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/private:gh-action-app
