name: Create feature branch

on:
  workflow_dispatch:   #Manual trigger
    inputs:
      branch_name:
        description: "New feature branch name (feature/ABC-123-desc)"
        required: true
        #default: "release-1.0"

env:
  PARENT_BRANCH: develop

permissions:
  contents: write

jobs:
  create-feature-branch:
    runs-on: self-hosted

    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ github.event.inputs.branch_name }}"
          #Save input to a global variable. 
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV 
          echo "Input branch name: ${BRANCH_NAME}" 

          # Allowed patterns
          PATTERN="^(feature|bugfix)\/[A-Z]+-[0-9]+-[a-z0-9-]+$|^release\/[0-9]+\.[0-9]+\.[0-9]+$"

          if [[ ! ${ BRANCH_NAME } =~ $PATTERN ]]; then
            echo "❌ Invalid branch name: ${ BRANCH_NAME }"
            echo "Allowed formats:"
            echo "  feature/ABC-123-description"
            echo "  bugfix/ABC-123-description"
            echo "  release/1.2.0"
            exit 1
          fi

          echo "✅ Branch name is valid"
       
      - name: Create and push branch
        run: |
          git checkout ${ PARENT_BRANCH }
          git checkout -b ${ BRANCH_NAME }
          git push origin ${ BRANCH_NAME }
