name: Create feature branch

on:
  #Enable manual trigger.
  workflow_dispatch:
    inputs:
      branch_name:
        description: "New feature branch name (feature/ABC-123-desc)"
        required: true
        #default: "release-1.0"

#Global environment variables.
env:
  PARENT_BRANCH: develop

permissions:
  contents: write

#A job has a sequential list of steps. Several jobs can be run in parallel or chained.
jobs:
  create-feature-branch:
    #Runner label.
    runs-on: self-hosted

    steps:
      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ github.event.inputs.branch_name }}"

          #Save input to a global variable. 
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV 
          echo "Input branch name: ${BRANCH_NAME}" 

          #Allowed patterns.
          PATTERN="^(feature|bugfix)\/[a-z]+-[0-9]+-[a-z0-9-]+$|^release\/[0-9]+\.[0-9]+\.[0-9]+$"

          if [[ ! ${BRANCH_NAME} =~ $PATTERN ]]; then
            echo "❌ Invalid branch name: ${BRANCH_NAME}"
            echo "Allowed formats:"
            echo "  feature/abc-123-description"
            echo "  bugfix/ABC-123-description"
            echo "  release/1.2.0"
            exit 1
          fi

          echo "✅ Branch name is valid"
       
      - name: Create and push branch
        run: |
          git checkout ${PARENT_BRANCH}
          git checkout -b ${BRANCH_NAME}
          git push origin ${BRANCH_NAME}
